config/routes.rb
Rails.application.routes.draw do
  resources :summaries

  resources :comments

  resources :favorites

  resources :votes

  devise_for :users
  resources :restaurants do
    	member do
	post 'upvote'
	end
end

resources :restaurants do
	member do
	post 'downvote'
end
end

root 'restaurants#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
belongs_to :restaurant
belongs_to :user

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
belongs_to :restaurant
belongs_to :user

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

has_many :votes, dependent: :destroy
has_many :comments, dependent: :destroy

validates :name, :address, :city, :state, :zip, presence: :true
validates :zip, numericality: {only_integer: true}
paginates_per 5

  def self.search(query)
     where( "name LIKE :query OR address LIKE :query OR city LIKE :query OR state LIKE :query", query: "%#{query}%")

  end

end

app/models/summary.rb
class Summary < ActiveRecord::Base
belongs_to :restaurant
belongs_to :user
has_many :comments
has_many :favorites
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
belongs_to :restaurant
belongs_to :user

def self.yes_votes(restaurant)  
Vote.where(:restaurantID => restaurant, :split => true).count 
end

def self.no_votes(restaurant)  
Vote.where(:restaurantID => restaurant, :split => false).count 
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!, :except => [:show, :search, :index]
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show]

  respond_to :html

  def index
    @comments = Comment.all
    respond_with(@comments)
  end

  def show
    respond_with(@comment)
  end

  def new
    @comment = Comment.new
    respond_with(@comment)
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
   respond_to do |format|
      if @comment.save
        format.html { redirect_to :back, notice: "Comment has been added." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
	rescue ActionController::RedirectBackError
	redirect_to restaurants_path
  end

  private
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def comment_params
      params.require(:comment).permit(:user_id, :restaurant_id, :comment)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_favorite, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @favorites = Favorite.all
    respond_with(@favorites)
  end

  def show
    respond_with(@favorite)
  end

  def new
    @favorite = Favorite.new
    respond_with(@favorite)
  end


  def create
    @favorite = Favorite.new(favorite_params)
   respond_to do |format|
      if @favorite.save
        format.html { redirect_to :back, notice: "Restaurant has been added to favorites"}
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @favorite.errors, status: :unprocessable_entity }
      end
    end

	rescue ActionController::RedirectBackError
	redirect_to restaurants_path
  end

  private
    def set_favorite
      @favorite = Favorite.find(params[:id])
    end

    def favorite_params
      params.require(:favorite).permit(:vote, :user_id, :restaurant_id)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  # GET /restaurants
  # GET /restaurants.json
  def index
      if params[:search]
      @restaurants = Restaurant.search(params[:search]).order("created_at DESC").page(params[:page])
    else
      @restaurants = Restaurant.order("name").page(params[:page])
    end
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to restaurants_path}
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :city, :state, :zip)
    end
end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  before_action :set_summary, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @summaries = Summary.all
    respond_with(@summaries)
  end

  def show
    respond_with(@summary)
  end

  def new
    @summary = Summary.new
    respond_with(@summary)
  end

  def create
    @summary = Summary.new(summary_params)
  respond_to do |format|
      if @summary.save
        format.html { redirect_to restaurants_path}
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @summary.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    def set_summary
      @summary = Summary.find(params[:id])
    end

    def summary_params
      params.require(:summary).permit(:user_id, :restaurant_id)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @votes = Vote.order("restaurantID, email, split")
    respond_with(@votes)
  end

  def show
    respond_with(@vote)
  end

  def new
    @vote = Vote.new
    respond_with(@vote)
  end

  def create
    @vote = Vote.create(vote_params)
    respond_to do |format|
      if @vote.save
        format.html { redirect_to :back}
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end	
    end

	rescue ActionController::RedirectBackError
	redirect_to root_path
  end

  private
    def set_vote
      @vote = Vote.find(params[:id])
    end

    def vote_params
      params.require(:vote).permit(:restaurantID, :email, :split)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/summaries_helper.rb
module SummariesHelper
end

app/helpers/user_controller_helper.rb
module UserControllerHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SplitTheCheck</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body">

<div id="banner">

<%= @page_title || "Split The Check" %>
<br><br>
<%= form_tag(restaurants_path, :method => "get") do %>

      <%= text_field_tag :search, params[:search], placeholder: "Search by name or location" %>
      <button type="submit">Search</button>

  <% end %>

<p id="login">
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :id => 'login' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :id => 'login'  %>
<% else %>
<%= link_to "Sign up", new_user_registration_path, :id => 'login'  %> |
  <%= link_to "Login", new_user_session_path, :id => 'login'  %>
<% end %>
</p>
</div>
<div id="side">
<ul>
<li><%= link_to 'Add A Restaurant', new_restaurant_path %></li>
<% if user_signed_in? %>
<li><%= link_to 'User Page', summaries_path %>
<% end %>
<li><%= link_to 'Home', restaurants_path %></li>
</ul>
</div>
<div id="body"></div>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="form">
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div id="form">

    <%= f.text_field :address, placeholder: "Address" %>
  </div>
  <div id="form">

    <%= f.text_field :city, placeholder: "City" %>
  </div>
  <div id="form">
    <%= f.text_field :state, :size => 2, :maxlength => 2, placeholder: "State" %> <%= f.text_field :zip, :size => 5, :maxlength => 5, placeholder: "Zip" %>
  </div>
  <div id="form">
    <%= f.submit %>
  </div>

<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<table>
  <thead>
    <tr id="titles">
      <th>Name</th>
      <th>Address</th>
      <th>Do They Split?</th>
      <th>Cast Your Vote</th>
<% if user_signed_in? %>
      <th>Favorite?</th>
      <th>Add A Comment</th>
<% end %>
    </tr>

  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>

      <tr>
        <td id="restaurantname"><%= link_to restaurant.name, restaurant %></td>
        <td id="address"><%= restaurant.address %><br>
        <%= restaurant.city %>
        <%= restaurant.state %> 
        <%= restaurant.zip %></td>
	<% if (Vote.yes_votes(restaurant.id) > Vote.no_votes(restaurant.id)) %>
	<td id="resultyes"><%= Vote.yes_votes(restaurant.id) %> said yes!<br>
	<%= Vote.no_votes(restaurant.id) %> said no!</td>
        <% else if (Vote.yes_votes(restaurant.id) == Vote.no_votes(restaurant.id)) %>
	<td id="resultsplit"><%= Vote.yes_votes(restaurant.id) %> said yes!<br>
	<%= Vote.no_votes(restaurant.id) %> said no!</td>
	<% else %>
	<td id="resultno"><%= Vote.yes_votes(restaurant.id) %> said yes!<br>
	<%= Vote.no_votes(restaurant.id) %> said no!</td>


	<% end %>
	<% end %>

<% if user_signed_in? %>

<td id="split"><%= button_to("Yes!", :action => "create", :controller => "votes", :vote => {:restaurantID => restaurant.id, :email => current_user.email, :split => 'true'}) %>

<%= button_to("No!", :action => "create", :controller => "votes", :vote => {:restaurantID => restaurant.id, :email => current_user.email, :split => 'false'}) %></td>
<td id="split">
<%= button_to("Favorite!", :action => "create", :controller => "favorites", :favorite => {:vote => 'true', :user_id => current_user.id, :restaurant_id => restaurant.id}) %></td>
</td>

<% else %>

<td id="split"><%= link_to "Login to vote", new_user_session_path, :class => 'navbar-link'  %></td>
<% end %>

<td id="split">    

<% if user_signed_in? %>
<%= form_for Comment.new do |f| %>

  <%= f.hidden_field :restaurant_id, :value => restaurant.id %><br />
  <%= f.text_field :comment, :placeholder=> "Enter Comment Here"%><br />

  <%= f.submit %>
<% end %>
<% end %>
</td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<div id="pagination"><%= paginate @restaurants %></div>  

app/views/restaurants/new.html.erb
<h1 id="form">Add a New Restaurant</h1>

<%= render 'form' %>

<div id="form"><%= link_to 'Back', restaurants_path %></div>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>
<div id="form">
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @restaurant.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @restaurant.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @restaurant.zip %>
</p>

<%= link_to 'Back', restaurants_path %>
</div>

app/views/summaries/_form.html.erb
<%= form_for(@summary) do |f| %>
  <% if @summary.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@summary.errors.count, "error") %> prohibited this summary from being saved:</h2>

      <ul>
      <% @summary.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :restaurant_id %><br>
    <%= f.text_field :restaurant_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/summaries/edit.html.erb
<h1>Editing summary</h1>

<%= render 'form' %>

<%= link_to 'Show', @summary %> |
<%= link_to 'Back', summaries_path %>

app/views/summaries/index.html.erb
<h1><%= current_user.email %>'s Summary Page</h1>
 <% if user_signed_in? %>
<table id="summarytable">
<% @user_votes = Vote.where("email = ?", User.find(current_user).email) %>
<thead>
    <tr>
      <th id="biggerheader">Restaurant Name</th>
      <th id="biggerheader">Do They Split?</th>
    </tr>
  </thead>
<% @user_votes.each do |user_vote| %>
<tr>
<td id="summarysplit"><%= link_to Restaurant.find(user_vote.restaurantID).name, Restaurant.find(user_vote.restaurantID) %></td>

<td id="summarysplit"><%= user_vote.split %></td>
<% end %>
</tr>

<thead>
    <tr>
      <th id="biggerheader" colspan="3">Favorite Restaurants</th>

    </tr>
  </thead>

<% @user_faves = Favorite.where('user_id = ?', current_user.id) %>
    <% @user_faves.each do |favorite| %>
      <tr>        
	        <td id="summarysplit"><%= link_to Restaurant.find(favorite.restaurant_id).name, Restaurant.find(favorite.restaurant_id) %></td>


      </tr>
<% end %>

<thead>
    <tr>
      <th id="biggerheader" colspan="3">Comments</th>
    </tr>
  </thead>

<% @user_comments = Comment.where('user_id = ?', current_user.id) %>
    <% @user_comments.each do |comment| %>
      <tr>        
	<td id="summarysplit"><%= link_to Restaurant.find(comment.restaurant_id).name, Restaurant.find(comment.restaurant_id) %></td>
	<td><%= Comment.find(comment.id).comment %></td>
      </tr>
<% end %>
</table>

<% else %>

<td id="split"><%= link_to "Login to view summary", new_user_session_path, :class => 'navbar-link'  %></td>
<% end %>

<br>

app/views/summaries/new.html.erb
<h1>New summary</h1>

<%= render 'form' %>

<%= link_to 'Back', summaries_path %>

app/views/summaries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @summary.user_id %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @summary.restaurant_id %>
</p>

<%= link_to 'Edit', edit_summary_path(@summary) %> |
<%= link_to 'Back', summaries_path %>